import eye from "@/assets/icons/eye.png"
import eyehide from "@/assets/icons/eye-hide.png"
import apple from "@/assets/icons/apple.png"
import facebook from "@/assets/icons/facebook.png"
import instagram from "@/assets/icons/instagram.png"
import google from "@/assets/icons/google.png"
import graduationcap from "@/assets/icons/graduationcap.png"
import code from "@/assets/icons/code.png"
import rocket from "@/assets/icons/rocket.png"
import trophy from "@/assets/icons/trophy.png"
import user from "@/assets/icons/user.png"
import circleUser from "@/assets/icons/circleUser.png"
import gear from "@/assets/icons/gear.png"
import arrowup from "@/assets/icons/arrowup.png"
import arrowback from "@/assets/icons/arrowback.png"
import darkmode from "@/assets/icons/darkmode.png"
import goal from "@/assets/icons/goal.png"
export default {eye,eyehide,apple,facebook,instagram,google, arrowback, gear,circleUser,graduationcap,code,rocket,trophy,user,arrowup,darkmode,goal}